In [1]:
%pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import cv2


In [3]:
import numpy as np

In [4]:
import pandas as pd
import os

In [5]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
re_img=cv2.resize(img,(500,300))

In [6]:
cv2.imshow("window",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
v=np.array([[1,2,1,2],[1,2,1,2]])

In [8]:
print(img)

[[[89 89 95]
  [89 89 95]
  [89 89 95]
  ...
  [90 90 96]
  [90 90 96]
  [90 90 96]]

 [[89 89 95]
  [89 89 95]
  [89 89 95]
  ...
  [90 90 96]
  [90 90 96]
  [90 90 96]]

 [[89 89 95]
  [89 89 95]
  [89 89 95]
  ...
  [90 90 96]
  [90 90 96]
  [90 90 96]]

 ...

 [[83 83 89]
  [83 83 89]
  [83 83 89]
  ...
  [65 67 75]
  [65 67 75]
  [65 67 75]]

 [[83 83 89]
  [83 83 89]
  [83 83 89]
  ...
  [65 67 75]
  [65 67 75]
  [65 67 75]]

 [[83 83 89]
  [83 83 89]
  [83 83 89]
  ...
  [66 68 76]
  [65 67 75]
  [65 67 75]]]


In [9]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")


re_img=cv2.resize(img,(500,400))
h=np.hstack((re_img,re_img))
k=np.vstack((h,h))
cv2.imshow("window",k)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
list_name=os.listdir(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets")
list_name

['Aether.webp',
 'emma.jpg',
 'Fee.pdf',
 'hrithil.jpeg',
 'logo.png',
 'Madhav Institute of Technology & Science, Gwalior (Deemed University) (M.P.), INDIA.pdf',
 'mm.png',
 'MMVY.pdf',
 'Nature.mp4',
 'red.avif',
 'Save.jpg',
 'Thor.jpg',
 'Timothee.jpg',
 'tom.jpeg',
 'year.jpeg']

In [11]:
for name in list_name:
    path="C:\\Users\\kanha\Documents\\saksham bansal\\stone paper\\image assets"
    img_name=path + "\\" +name
    img=cv2.imread(img_name)
    if img is None:
        print(f"❌ Could not read image: {img_name}")
        continue
    img=cv2.resize(img,(500,600))
    cv2.imshow("Saksham",img)
    cv2.waitKey(0)
cv2.destroyAllWindows()
    

❌ Could not read image: C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Fee.pdf
❌ Could not read image: C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Madhav Institute of Technology & Science, Gwalior (Deemed University) (M.P.), INDIA.pdf
❌ Could not read image: C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\MMVY.pdf
❌ Could not read image: C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Nature.mp4
❌ Could not read image: C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\red.avif


In [12]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg",0)


re_img=cv2.resize(img,(500,400))
h=np.hstack((re_img,re_img))
k=np.vstack((h,h))
cv2.imshow("window",k)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg",0)


re_img=cv2.resize(img,(500,400))
txt=cv2.putText(re_img,"Timothee",(50,50),2,2,(255,0,2),3,4)
txt=cv2.putText(re_img,"Timothee",(50,50),2,2,(255,0,2),3,4,True)
cv2.imshow("window",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")


re_img=cv2.resize(img,(500,400))

circle_img=cv2.circle(re_img,(250,150),90,(0,255,0),4,16)
cv2.imshow("window",circle_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")


re_img=cv2.resize(img,(500,400))

elipse_img=cv2.ellipse(re_img,(250,150),(50,100),30,0,360,(0,255,0),4,69)
cv2.imshow("window",elipse_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")


re_img=cv2.resize(img,(500,400))

new_img=cv2.polylines(re_img,pts=[np.array([[100,100],[100,200],[200,100],[300,600]])],isClosed=True,color=(0,255,0),thickness=4,lineType=1)
cv2.imshow("window",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img2=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\emma.jpg")

re_img=cv2.resize(img,(500,400))
re_img2=cv2.resize(img2,(500,400))

new_img=cv2.addWeighted(re_img,1,re_img2,2,1)
cv2.imshow("window",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img2=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\emma.jpg")

re_img=cv2.resize(img,(500,400))
re_img2=cv2.resize(img2,(500,400))

new_img=cv2.subtract(re_img,re_img2)
cv2.imshow("window",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# Bitwise (and,or,not,xor)
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img2=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\emma.jpg")

re_img=cv2.resize(img,(500,400))
re_img2=cv2.resize(img2,(500,400))

new_img=cv2.bitwise_or(re_img,re_img2)
cv2.imshow("window",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:

img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")

re_img=cv2.resize(img,(500,400))

new_img=cv2.Canny(re_img,200,200)
cv2.imshow("window",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:

img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")

re_img=cv2.resize(img,(500,400))

new_img=cv2.GaussianBlur(re_img,(9,9),0)
cv2.imshow("window",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:

img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")

re_img=cv2.resize(img,(500,400))
img1=cv2.copyMakeBorder(re_img,20,20,20,20,cv2.BORDER_CONSTANT,None,value=1)


cv2.imshow("window",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
cap=cv2.VideoCapture(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Nature.mp4")
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(600,600))
        cv2.imshow("window",frame)
        if cv2.waitKey(30) & 0xff==ord('p'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

In [24]:
cap=cv2.VideoCapture(0)
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(600,600))
        cv2.imshow("window",frame)
        if cv2.waitKey(30) & 0xff==ord('p'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

In [25]:
cap=cv2.VideoCapture(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Nature.mp4")
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(600,600))
        cv2.imshow("window",frame)
        if cv2.waitKey(2) & 0xff==ord('p'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

In [26]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")


print(img.shape)

(755, 1000, 3)


In [27]:
new=cv2.pyrDown(img)
print(new.shape)

(378, 500, 3)


In [28]:
cv2.imshow("widow",img)
cv2.imshow("window",new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img=cv2.resize(img,(600,600))
m=np.float32([[1,0,50],[0,1,50]])
new=cv2.warpAffine(img,m,(600,600))
cv2.imshow("widow",new)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
m

array([[ 1.,  0., 50.],
       [ 0.,  1., 50.]], dtype=float32)

In [31]:
cap=cv2.VideoCapture(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Nature.mp4")
sub_m=cv2.createBackgroundSubtractorKNN(detectShadows=True)
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(600,600))
        sub_v=sub_m.apply(frame)
        cv2.imshow("wi",sub_v)
        cv2.imshow("window",frame)
        if cv2.waitKey(2) & 0xff==ord('p'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

In [32]:
cap=cv2.VideoCapture(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Nature.mp4")

c=0
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.resize(frame,(600,600))
        file_name="C://Users//kanha//OneDrive//Pictures//Faltu//org_img_"+str(c)+'.png'
        cv2.imwrite(file_name,frame)
        cv2.imshow("wi",frame)
        c+=1
        
        if cv2.waitKey(2) & 0xff==ord('p'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()


In [33]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img=cv2.resize(img,(600,600))
new=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("widow",new)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img=cv2.resize(img,(600,600))
print(img.shape)
crop=img[100:400,120:400]
cv2.imshow("widow",crop)

cv2.waitKey(0)
cv2.destroyAllWindows()

(600, 600, 3)


In [35]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img=cv2.resize(img,(600,600))
new_img=np.ones((500,500,3),np.uint8)*0
cv2.imshow("widow",new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [36]:
def color(x):
    pass

In [37]:
img=np.zeros((500,500,3),np.uint8)*255

cv2.namedWindow("colour")
cv2.createTrackbar("R","colour",0,255,color)
cv2.createTrackbar("G","colour",0,255,color)
cv2.createTrackbar("B","colour",0,255,color)

while True:
    cv2.imshow("colour",img)
    if cv2.waitKey(1)& 0xff==ord("p"):
        break
    r=cv2.getTrackbarPos("R","colour")
    g=cv2.getTrackbarPos("G","colour")
    b=cv2.getTrackbarPos("B","colour")
    img[:]=[b,g,r]

cv2.destroyAllWindows()


In [38]:
img=np.zeros((500,500,3),np.uint8)*255

cv2.namedWindow("bar")
cv2.createTrackbar("on","bar",0,100,color)


while True:
    cv2.imshow("bar",img)
    if cv2.waitKey(1)& 0xff==ord("p"):
        break
    on=cv2.getTrackbarPos("on","bar")
    img[:]=[on,0,0]

cv2.destroyAllWindows()


In [39]:
import cv2
img = cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Save.jpg")
crop = img[50:350, 180:400]   # (300 x 220)
dest_h = 350 - 50             # 300
dest_w = 600 - 400            # 200
crop_resized = cv2.resize(crop, (dest_w, dest_h))
img[50:350, 400:600] = crop_resized
cv2.imshow("window", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [40]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img=cv2.resize(img,(600,600))
img=cv2.transpose(img)
cv2.imshow("widow",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
cap=cv2.VideoCapture(0)
f=cv2.VideoWriter_fourcc(*"XVID")
out=cv2.VideoWriter("demo.mp4",f,40.0,(640,480),0)
c=0
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        frame=cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow("wi",frame)
        c+=1
        
        if cv2.waitKey(2) & 0xff==ord('p'):
            break
    else:
        break
cap.release()
out.release()
cv2.destroyAllWindows()


In [42]:
import cv2
import numpy as np
import pandas as pd

In [43]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img=cv2.resize(img,(600,600))
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
_,th=cv2.threshold(img,100,255,cv2.THRESH_OTSU)
cv2.imshow("widow",th)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [44]:
%pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [45]:
import matplotlib.pyplot as plt

In [46]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img=cv2.resize(img,(600,600))
_,th=cv2.threshold(img,100,255,cv2.THRESH_OTSU)
his=cv2.calcHist([img],[0],None,[256],[0,255])
hi=cv2.calcHist([th],[0],None,[256],[0,256])
plt.subplot(2,1,1)
plt.plot(his)
plt.subplot(2,1,2)
plt.plot(hi)
plt.show()
cv2.imshow("widow",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.12.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\thresh.cpp:1633: error: (-2:Unspecified error) in function 'double __cdecl cv::threshold(const class cv::_InputArray &,const class cv::_OutputArray &,double,double,int)'
> THRESH_OTSU mode:
>     'src_type == CV_8UC1 || src_type == CV_16UC1'
> where
>     'src_type' is 16 (CV_8UC3)


In [ ]:
def python(event,x,y,f,p):
    if event==cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img,(x,y),5,(0,0,3),4)
    elif event==cv2.EVENT_RBUTTONDOWN:
        cv2.rectangle(img,(x,y),(x+20,y+20),(0,45,0),4)    


In [ ]:
img=np.ones((600,600,3),np.uint8)*255
cv2.namedWindow('widow')
cv2.setMouseCallback(window_name='widow',on_mouse=python)
while True:
    cv2.imshow("widow",img)
    if cv2.waitKey(25) & 0xff==ord("p"):
        break
cv2.destroyAllWindows()

In [ ]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img=cv2.resize(img,(600,600))
img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
r,th=cv2.threshold(img1,250,255,cv2.THRESH_BINARY)
c,h=cv2.findContours(th,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
new_img=cv2.drawContours(img,c,-1,(255,0,0),3)
cv2.imshow("widow",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [47]:
import cv2
import numpy as np

img = cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Timothee.jpg")
img = cv2.resize(img, (600, 600))

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, th = cv2.threshold(gray, 7, 255, cv2.THRESH_BINARY)

contours, hierarchy = cv2.findContours(
    th, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE
)

# Draw all contours once
cv2.drawContours(img, contours, -1, (255, 0, 0), 3)
ar=[]
# Draw centroid for each contour
for cnt in contours:
    m = cv2.moments(cnt)
    if m["m00"] != 0:
        x = int(m["m10"] / m["m00"])
        y = int(m["m01"] / m["m00"])
        cv2.circle(img, (x, y), 4, (0, 0, 255), -1)
        a=cv2.contourArea(cnt)
        ar.append(a)
        ep=0.1*cv2.arcLength(cnt,True)
        d=cv2.approxPolyDP(cnt,ep,True)
        h=cv2.convexHull(d)
        x,y,w,h=cv2.boundingRect(h)
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),5)
cv2.imshow("window", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [48]:
def noth(x):
    pass

In [49]:
cap=cv2.VideoCapture(0)
f=cv2.VideoWriter_fourcc(*"XVID")
out=cv2.VideoWriter("demo.mp4",f,40.0,(640,480),0)
c=0
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        frame=cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow("wi",frame)
        c+=1
        
        if cv2.waitKey(2) & 0xff==ord('p'):
            break
    else:
        break
cap.release()
out.release()
cv2.destroyAllWindows()


In [1]:
import cv2

In [2]:
import numpy as np

In [ ]:
cv2.namedWindow("widow")
cv2.namedWindow("mask")
cv2.namedWindow("res")
cv2.namedWindow("thr")
cv2.createTrackbar("threshold","widow",0,255,noth)

cv2.createTrackbar("lb","widow",0,179,noth)
cv2.createTrackbar("lg","widow",0,255,noth)
cv2.createTrackbar("lr","widow",0,255,noth)

cv2.createTrackbar("hb","widow",255,255,noth)
cv2.createTrackbar("hg","widow",255,255,noth)
cv2.createTrackbar("hr","widow",255,255,noth)
cap=cv2.VideoCapture(0)
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        th=cv2.getTrackbarPos("threshold","widow")
        lb=cv2.getTrackbarPos("lb","widow")
        lg=cv2.getTrackbarPos("lg","widow")
        lr=cv2.getTrackbarPos("lr","widow")
        hb=cv2.getTrackbarPos("hb","widow")
        hg=cv2.getTrackbarPos("hg","widow")
        hr=cv2.getTrackbarPos("hr","widow")
        lower=np.array([lb,lg,lr])
        upper=np.array([hb,hg,hr])
        




        frame=cv2.flip(frame,1)
        frame=cv2.resize(frame,(400,400))
        hsv=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
        m=cv2.inRange(hsv,lower,upper)
        res=cv2.bitwise_and(frame,frame,mask=m)
        fr=cv2.bitwise_not(res)

        _,thi=cv2.threshold(m,th,255,cv2.THRESH_BINARY)
        cnt,hr=cv2.findContours(thi,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
        cv2.drawContours(frame,cnt,-1,(255,0,0),2)
        cv2.imshow("thr",thi)
        cv2.imshow("res",res)
        mask_gray = cv2.GaussianBlur(m, (15, 15), 0)
        cv2.imshow("mask", mask_gray)
        cv2.imshow("widow",frame)
        
        
        
        if cv2.waitKey(25) & 0xff==ord('p'):
            break
    else:
        break
cap.release()

cv2.destroyAllWindows()

NameError: name 'noth' is not defined

: 

In [53]:
cap=cv2.VideoCapture(0)
f=cv2.VideoWriter_fourcc(*"XVID")
out=cv2.VideoWriter("demo.mp4",f,40.0,(640,480),0)
c=0
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        frame=cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow("wi",frame)
        c+=1
        
        if cv2.waitKey() & 0xff==ord('p'):
            break
    else:
        break
cap.release()
out.release()
cv2.destroyAllWindows()


In [ ]:
cv2.namedWindow("widow")
cv2.namedWindow("mask")
cv2.namedWindow("res")
cv2.createTrackbar("threshold","widow",0,255,noth)

cv2.createTrackbar("lb","widow",0,179,noth)
cv2.createTrackbar("lg","widow",0,255,noth)
cv2.createTrackbar("lr","widow",0,255,noth)

cv2.createTrackbar("hb","widow",255,255,noth)
cv2.createTrackbar("hg","widow",255,255,noth)
cv2.createTrackbar("hr","widow",255,255,noth)
cap=cv2.VideoCapture(0)
while cap.isOpened():
    r,frame=cap.read()
    if r==True:
        th=cv2.getTrackbarPos("threshold","widow")
        lb=cv2.getTrackbarPos("lb","widow")
        lg=cv2.getTrackbarPos("lg","widow")
        lr=cv2.getTrackbarPos("lr","widow")
        hb=cv2.getTrackbarPos("hb","widow")
        hg=cv2.getTrackbarPos("hg","widow")
        hr=cv2.getTrackbarPos("hr","widow")
        lower=np.array([lb,lg,lr])
        upper=np.array([hb,hg,hr])
        




        frame=cv2.flip(frame,1)
        frame=cv2.resize(frame,(400,400))
        hsv=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
        m=cv2.inRange(hsv,lower,upper)
        res=cv2.bitwise_or(frame,frame,mask=m)
        cv2.imshow("res",res)
        cv2.imshow("mask",m)
        cv2.imshow("widow",frame)
        
        
        
        if cv2.waitKey(1) & 0xff==ord('p'):
            break
    else:
        break
cap.release()

cv2.destroyAllWindows()

NameError: name 'noth' is not defined

: 

In [4]:
import cv2
import numpy as np

In [56]:
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Thor.jpg")
gry=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edg=cv2.Canny(gry,20,250)
lines=cv2.HoughLines(edg,1,np.pi/180,200)
for r,th in lines[0]:
    a=np.cos(th)
    b=np.sin(th)
    x0=a*r
    y0=b*r
    x1=int(x0+1000*(-b))
    y1=int(y0+(1000)*(a))
    x2=int(x0-1000*(-b))
    y2=int(y0-1000*(a))
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imshow("window", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [57]:
## y=mx+c
img=cv2.imread(r"C:\Users\kanha\Documents\saksham bansal\stone paper\image assets\Thor.jpg")
gry=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edg=cv2.Canny(gry,20,250)
lines=cv2.HoughLinesP(edg,1,np.pi/180,200,minLineLength=190,maxLineGap=100)
for i in lines:
   
    x1,y1,x2,y2=i[0]
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imshow("window", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np

In [3]:
import cv2
import numpy as np

img = cv2.imread(r"C:\Users\kanha\OneDrive\Pictures\group.png")
template = cv2.imread(r"C:\Users\kanha\OneDrive\Pictures\ansh.png")

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray_template = cv2.cvtColor(template, cv2.COLOR_BGR2GRAY)

orb = cv2.ORB_create(1000)

kp1, des1 = orb.detectAndCompute(gray_template, None)
kp2, des2 = orb.detectAndCompute(gray_img, None)

bf = cv2.BFMatcher(cv2.NORM_HAMMING)

matches = bf.knnMatch(des1, des2, k=2)

# Lowe's ratio test (important)
good = []
for m, n in matches:
    if m.distance < 0.75 * n.distance:
        good.append(m)

print("Good matches:", len(good))

if len(good) > 10:

    src_pts = np.float32([kp1[m.queryIdx].pt for m in good]).reshape(-1,1,2)
    dst_pts = np.float32([kp2[m.trainIdx].pt for m in good]).reshape(-1,1,2)

    M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)

    h, w = gray_template.shape
    pts = np.float32([[0,0],[0,h],[w,h],[w,0]]).reshape(-1,1,2)
    dst = cv2.perspectiveTransform(pts, M)

    img = cv2.polylines(img, [np.int32(dst)], True, (0,255,0), 3)

else:
    print("Not enough matches found")

cv2.imshow("Detected Person", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


Good matches: 3
Not enough matches found


In [115]:
gry1.shape

(145, 97)

In [116]:
print(np.max(res))


0.48289272
